/**
 * Swallern Visual System v1 — Conceptual Assets Registry
 * Section 7: Abstract and systemic concepts represented via approved Swallern visual language.
 * Avoids generic stock metaphors in favor of structured, clear educational abstractions.
 */

import { VisualAsset } from './assets';
import { SWALLERN_VISUAL_STYLE_V1 } from './tokens';

export interface ConceptMetaphorDefinition {
  conceptId: string;
  name: string;
  metaphor: string;
  representationRules: string[];
  approvedColors: string[];
}

export const SWALLERN_CONCEPT_METAPHORS: Record<string, ConceptMetaphorDefinition> = {
  data: {
    conceptId: 'data',
    name: 'Data & Information',
    metaphor: 'Organized data particles, neatly indexed cards, or structured byte packets',
    representationRules: [
      'Use rounded glowing cards or soft geometric cubes',
      'Show clear orderly arrangement rather than chaotic numbers',
      'Use teal and blue highlights with subtle motion streaks',
    ],
    approvedColors: ['#3B82F6', '#0D9488', '#F8FAFC'],
  },
  network: {
    conceptId: 'network',
    name: 'Network & Topology',
    metaphor: 'Luminescent interconnected circular nodes with pulse lines',
    representationRules: [
      'Nodes are clean rounded circles with contrasting core dots',
      'Connection links use smooth curved vectors or dotted dynamic paths',
      'Avoid realistic physical wire tangles',
    ],
    approvedColors: ['#3B82F6', '#8B5CF6', '#10B981'],
  },
  energy: {
    conceptId: 'energy',
    name: 'Flowing Energy & Power',
    metaphor: 'Controlled glowing streams with soft particle sparks',
    representationRules: [
      'Soft radiant lines with rounded wave paths',
      'Warm amber or electric yellow-cyan luminescence',
      'Never harsh jagged spikes or chaotic lightning',
    ],
    approvedColors: ['#F59E0B', '#06B6D4', '#F97316'],
  },
  communication: {
    conceptId: 'communication',
    name: 'Communication & Dialogue',
    metaphor: 'Synchronized radio waves, dialogue cards, and signal pulses between nodes',
    representationRules: [
      'Concentric expanding rounded arcs',
      'Clean speech cards with minimal iconography',
      'Clear directional flow from sender to receiver',
    ],
    approvedColors: ['#3B82F6', '#10B981', '#F59E0B'],
  },
  growth: {
    conceptId: 'growth',
    name: 'Growth & Progression',
    metaphor: 'Progressive sequential visual stages from seed/base to full flourishing bloom',
    representationRules: [
      'Left-to-right ascending visual stages',
      'Soft upward arrows and expanding plant sprout or geometric bar motifs',
      'Fresh green and golden highlight accents',
    ],
    approvedColors: ['#10B981', '#F59E0B', '#0D9488'],
  },
  algorithm: {
    conceptId: 'algorithm',
    name: 'Algorithm & Logic Decision',
    metaphor: 'Transparent step-by-step logic pathways with branching decision junctions',
    representationRules: [
      'Clean flow blocks with rounded corners',
      'Clear Yes/No conditional split paths',
      'Purple and blue logic pulses flowing through the pathway',
    ],
    approvedColors: ['#8B5CF6', '#3B82F6', '#10B981'],
  },
  artificial_intelligence: {
    conceptId: 'artificial_intelligence',
    name: 'AI & Neural Processing',
    metaphor: 'Multi-layer neural network with glowing synaptic weights and feature maps',
    representationRules: [
      'Layered vertical columns of circular neurons',
      'Weighted connection lines glowing with activation intensity',
      'Harmonious deep purple and bright cyan aesthetic',
    ],
    approvedColors: ['#8B5CF6', '#06B6D4', '#EC4899'],
  },
  cloud_computing: {
    conceptId: 'cloud_computing',
    name: 'Cloud Infrastructure',
    metaphor: 'Soft modular cloud container housing organized server blade cards',
    representationRules: [
      'Gentle rounded vector cloud shape with subtle glassmorphic backdrop',
      'Internal glowing server blades and database cylinders',
      'Dotted bidirectional upload/download sync arrows',
    ],
    approvedColors: ['#3B82F6', '#0D9488', '#EFF6FF'],
  },
  gravity: {
    conceptId: 'gravity',
    name: 'Gravitational Force',
    metaphor: 'Curved spatial spacetime grid depressed under mass with orbital vector paths',
    representationRules: [
      'Gentle warped coordinate grid lines',
      'Smooth concentric orbital ellipses with direction arrows',
      'Deep navy backdrop with glowing gravitational vectors',
    ],
    approvedColors: ['#0F172A', '#3B82F6', '#8B5CF6'],
  },
  supply_and_demand: {
    conceptId: 'supply_and_demand',
    name: 'Supply & Demand Balance',
    metaphor: 'Balanced scale with intersecting upward and downward dynamic curves',
    representationRules: [
      'Clean crossing supply (green) and demand (blue) curves with equilibrium point dot',
      'Equilibrium marker highlighted with golden halo',
      'Educational clarity over complex mathematical notation',
    ],
    approvedColors: ['#10B981', '#3B82F6', '#F59E0B'],
  },
  security: {
    conceptId: 'security',
    name: 'Cybersecurity & Shielding',
    metaphor: 'Luminescent protective vector shield with cryptographic lock core',
    representationRules: [
      'Rounded geometric hexagonal or shield contour',
      'Glowing cryptographic padlock core in golden yellow',
      'Subtle perimeter barrier grid that blocks red hazard vectors',
    ],
    approvedColors: ['#10B981', '#F59E0B', '#3B82F6'],
  },
  time: {
    conceptId: 'time',
    name: 'Time & Chronology',
    metaphor: 'Linear progress timeline with glowing temporal milestone nodes',
    representationRules: [
      'Horizontal smooth track with chronological event cards',
      'Past, present, and future highlighted with distinct tonal saturation',
      'Soft clockwise rotational motion indicator',
    ],
    approvedColors: ['#3B82F6', '#F59E0B', '#8B5CF6'],
  },
};

/**
 * Master Canonical Conceptual Visual Assets
 */
export const CANONICAL_CONCEPT_ASSETS: VisualAsset[] = [
  {
    id: 'concept_data_particles_v1',
    version: '1.0',
    name: 'data_particles',
    displayName: 'Organized Data Stream',
    family: 'concept',
    categoryIds: ['technology', 'artificial_intelligence', 'science'],
    domainIds: ['datasets', 'software', 'programming'],
    tags: ['data', 'packets', 'bytes', 'stream', 'information', 'flow'],
    aliases: ['data packets', 'byte stream', 'information packets'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['server_v1', 'laptop_v1', 'router_v1', 'cloud_network_v1'],
    description: 'Neatly organized glowing data cards and geometric byte particles moving along a defined bus pathway.',
    defaultColor: '#3B82F6',
    metadata: {
      metaphorId: 'data',
    },
  },
  {
    id: 'concept_network_nodes_v1',
    version: '1.0',
    name: 'network_nodes',
    displayName: 'Interconnected Network Mesh',
    family: 'concept',
    categoryIds: ['technology', 'communication_media', 'science'],
    domainIds: ['networking', 'internet', 'telecommunications'],
    tags: ['network', 'mesh', 'nodes', 'connections', 'links', 'topology'],
    aliases: ['network graph', 'connected nodes', 'mesh network'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['router_v1', 'server_v1', 'smartphone_v1', 'laptop_v1'],
    description: 'Balanced constellation of connected circular nodes with glowing transmission pulses.',
    defaultColor: '#0D9488',
    metadata: {
      metaphorId: 'network',
    },
  },
  {
    id: 'concept_energy_flow_v1',
    version: '1.0',
    name: 'energy_flow',
    displayName: 'Flowing Energy Stream',
    family: 'concept',
    categoryIds: ['energy', 'science', 'engineering'],
    domainIds: ['renewable', 'physics', 'storage_grid'],
    tags: ['energy', 'power', 'flow', 'electricity', 'current', 'luminescence'],
    aliases: ['power stream', 'electric current', 'energy pulse'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['battery_v1', 'solar_panel_v1', 'circuit_board_v1'],
    description: 'Smooth, warm glowing wave stream depicting controlled transmission of electrical and thermal energy.',
    defaultColor: '#F59E0B',
    metadata: {
      metaphorId: 'energy',
    },
  },
  {
    id: 'concept_growth_stages_v1',
    version: '1.0',
    name: 'growth_stages',
    displayName: 'Sequential Growth Progression',
    family: 'concept',
    categoryIds: ['nature_environment', 'agriculture', 'business', 'education'],
    domainIds: ['crops', 'botany', 'management', 'pedagogy'],
    tags: ['growth', 'progression', 'stages', 'development', 'scaling', 'cycle'],
    aliases: ['growth sequence', 'progression stages', 'development curve'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['seed_v1', 'soil_v1', 'watering_can_v1', 'swallern_bear_v1'],
    description: 'Four ascending visual milestones illustrating organic or organizational progress.',
    defaultColor: '#10B981',
    metadata: {
      metaphorId: 'growth',
    },
  },
  {
    id: 'concept_ai_neural_net_v1',
    version: '1.0',
    name: 'ai_neural_net',
    displayName: 'Neural Network Layer Architecture',
    family: 'concept',
    categoryIds: ['artificial_intelligence', 'technology'],
    domainIds: ['deep_learning', 'machine_learning', 'algorithms'],
    tags: ['ai', 'neural_network', 'deep_learning', 'weights', 'layers', 'synapse'],
    aliases: ['neural net', 'deep neural network', 'mlp layers'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'diagram',
    compatibleWith: ['robot_v1', 'laptop_v1', 'server_v1'],
    description: 'Input, hidden, and output neuron layers with glowing activation weight connections.',
    defaultColor: '#8B5CF6',
    metadata: {
      metaphorId: 'artificial_intelligence',
    },
  },
  {
    id: 'concept_cloud_infrastructure_v1',
    version: '1.0',
    name: 'cloud_infrastructure',
    displayName: 'Cloud Computing Architecture',
    family: 'concept',
    categoryIds: ['technology'],
    domainIds: ['cloud_computing', 'internet'],
    tags: ['cloud', 'datacenter', 'servers', 'sync', 'upload', 'download'],
    aliases: ['cloud server', 'cloud storage', 'distributed cloud'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['server_v1', 'laptop_v1', 'smartphone_v1'],
    description: 'Stylized glassmorphic cloud enclosing miniature server blades with syncing directional vectors.',
    defaultColor: '#3B82F6',
    metadata: {
      metaphorId: 'cloud_computing',
    },
  },
  {
    id: 'concept_supply_demand_v1',
    version: '1.0',
    name: 'supply_demand',
    displayName: 'Supply & Demand Equilibrium',
    family: 'concept',
    categoryIds: ['finance_economics', 'business'],
    domainIds: ['macroeconomics', 'sales_commerce'],
    tags: ['supply', 'demand', 'equilibrium', 'economics', 'market', 'balance'],
    aliases: ['supply and demand curve', 'market equilibrium', 'price curves'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'diagram',
    compatibleWith: ['money_coins_v1', 'bank_building_v1'],
    description: 'Clean intersecting curves demonstrating economic price discovery and equilibrium point.',
    defaultColor: '#10B981',
    metadata: {
      metaphorId: 'supply_and_demand',
    },
  },
  {
    id: 'concept_security_shield_v1',
    version: '1.0',
    name: 'security_shield',
    displayName: 'Cybersecurity Shield & Lock',
    family: 'concept',
    categoryIds: ['technology', 'finance_economics'],
    domainIds: ['cybersecurity', 'banking'],
    tags: ['security', 'shield', 'encryption', 'lock', 'firewall', 'protection'],
    aliases: ['security barrier', 'firewall shield', 'encryption lock'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['router_v1', 'server_v1', 'laptop_v1', 'credit_card_v1'],
    description: 'Protective teal shield emblazoned with a golden glowing lock icon.',
    defaultColor: '#0D9488',
    metadata: {
      metaphorId: 'security',
    },
  },
];
