/**
 * Swallern Visual System v1 — Initial Foundational Asset Manifests
 * Section 30: Planned generation manifests for the 6 foundational asset packs.
 * Establishes the systematic roadmap for visual expansion without generating massive files upfront.
 */

import { VisualAssetFamily } from './assets';

export interface FoundationManifestItem {
  id: string;
  name: string;
  displayName: string;
  family: VisualAssetFamily;
  categoryIds: string[];
  domainIds?: string[];
  tags: string[];
  aliases: string[];
  description: string;
  generationPrompt: string;
  targetComplexity: 'simple' | 'moderate' | 'complex' | 'diagram' | 'scene';
}

export interface FoundationAssetPack {
  packId: string;
  title: string;
  description: string;
  priority: number;
  items: FoundationManifestItem[];
}

export const FOUNDATION_PACK_1_UNIVERSAL: FoundationAssetPack = {
  packId: 'pack_1_universal',
  title: 'Pack 1 — Universal Learning Essentials',
  description: 'Ubiquitous human characters, canonical mascot, furniture, and fundamental everyday objects.',
  priority: 1,
  items: [
    {
      id: 'swallern_bear_v1',
      name: 'swallern_bear',
      displayName: 'Swallern Bear Mascot',
      family: 'mascot',
      categoryIds: ['education', 'everyday_life'],
      domainIds: ['classroom_learning'],
      tags: ['mascot', 'bear', 'student', 'guide'],
      aliases: ['bear', 'swallern bear'],
      description: 'Canonical Swallern mascot with blue backpack and warm friendly expression.',
      generationPrompt: 'Swallern Bear mascot, soft vector geometry, chubby friendly torso, blue backpack with yellow zippers, warm smile, crisp isolated vector.',
      targetComplexity: 'simple',
    },
    {
      id: 'person_learner_v1',
      name: 'person_learner',
      displayName: 'Student Learner',
      family: 'character',
      categoryIds: ['education', 'everyday_life'],
      domainIds: ['classroom_learning'],
      tags: ['person', 'student', 'learner', 'human'],
      aliases: ['student', 'learner', 'pupil'],
      description: 'Friendly student in clean modern hoodie holding a study notebook.',
      generationPrompt: 'Swallern Visual System v1 character, friendly student learner, rounded vector style, soft pastel palette, clean silhouette.',
      targetComplexity: 'moderate',
    },
    {
      id: 'book_stack_v1',
      name: 'book_stack',
      displayName: 'Stack of Educational Books',
      family: 'object',
      categoryIds: ['education', 'literature_language'],
      domainIds: ['classroom_learning'],
      tags: ['books', 'stack', 'library', 'study'],
      aliases: ['book stack', 'pile of books', 'reading books'],
      description: 'Neatly organized stack of colorful hardcover books.',
      generationPrompt: 'Stack of 3 colorful educational books, Swallern blue, teal, and yellow covers, soft rounded corners, clean vector.',
      targetComplexity: 'simple',
    },
    {
      id: 'desk_study_v1',
      name: 'desk_study',
      displayName: 'Wooden Study Desk',
      family: 'object',
      categoryIds: ['education', 'everyday_life'],
      domainIds: ['classroom_learning', 'home_daily'],
      tags: ['desk', 'table', 'study', 'furniture'],
      aliases: ['study desk', 'school desk'],
      description: 'Smooth wooden desk with clean legs.',
      generationPrompt: 'Minimalist wooden student study desk, light oak finish, soft shadows, Swallern v1 vector style.',
      targetComplexity: 'simple',
    },
    {
      id: 'chair_study_v1',
      name: 'chair_study',
      displayName: 'Ergonomic Study Chair',
      family: 'object',
      categoryIds: ['education', 'everyday_life'],
      domainIds: ['classroom_learning', 'home_daily'],
      tags: ['chair', 'seat', 'furniture'],
      aliases: ['desk chair', 'study chair'],
      description: 'Modern rounded ergonomic desk chair.',
      generationPrompt: 'Modern navy desk chair, rounded form, supportive backrest, clean vector silhouette.',
      targetComplexity: 'simple',
    },
    {
      id: 'clock_analog_v1',
      name: 'clock_analog',
      displayName: 'Analog Wall Clock',
      family: 'object',
      categoryIds: ['education', 'everyday_life'],
      domainIds: ['classroom_learning', 'home_daily'],
      tags: ['clock', 'time', 'hours', 'minutes'],
      aliases: ['wall clock', 'analog clock'],
      description: 'Circular wall clock with readable hour numerals.',
      generationPrompt: 'Clean round educational wall clock, 12-hour markings, distinct hour and minute hands, high legibility.',
      targetComplexity: 'simple',
    },
    {
      id: 'house_home_v1',
      name: 'house_home',
      displayName: 'Residential House',
      family: 'object',
      categoryIds: ['everyday_life', 'architecture_construction'],
      domainIds: ['home_daily', 'building_design'],
      tags: ['house', 'home', 'building', 'residential'],
      aliases: ['home', 'residence', 'family house'],
      description: 'Friendly suburban house with pitched roof and welcoming front door.',
      generationPrompt: 'Friendly rounded home house illustration, pitched blue roof, warm lit windows, clean vector.',
      targetComplexity: 'moderate',
    },
    {
      id: 'car_vehicle_v1',
      name: 'car_vehicle',
      displayName: 'Compact Electric Car',
      family: 'object',
      categoryIds: ['transportation', 'everyday_life', 'energy'],
      domainIds: ['road', 'renewable'],
      tags: ['car', 'vehicle', 'ev', 'automobile'],
      aliases: ['electric car', 'automobile', 'passenger car'],
      description: 'Aerodynamic rounded electric car in teal.',
      generationPrompt: 'Sleek compact electric car, smooth rounded curves, teal body, silver hubcaps, Swallern v1 style.',
      targetComplexity: 'simple',
    },
    {
      id: 'tree_oak_v1',
      name: 'tree_oak',
      displayName: 'Deciduous Shade Tree',
      family: 'object',
      categoryIds: ['nature_environment', 'agriculture'],
      domainIds: ['botany', 'wildlife'],
      tags: ['tree', 'nature', 'leaves', 'foliage', 'oak'],
      aliases: ['oak tree', 'shade tree', 'green tree'],
      description: 'Lush green leafy deciduous tree with sturdy brown trunk.',
      generationPrompt: 'Friendly rounded oak tree, emerald green canopy clouds, warm brown trunk, clean vector outline.',
      targetComplexity: 'simple',
    },
  ],
};

export const FOUNDATION_PACK_2_TECHNOLOGY: FoundationAssetPack = {
  packId: 'pack_2_technology',
  title: 'Pack 2 — Technology & Computing Essentials',
  description: 'Digital hardware, networking equipment, microchips, servers, and computational nodes.',
  priority: 2,
  items: [
    {
      id: 'laptop_v1',
      name: 'laptop',
      displayName: 'Modern Laptop',
      family: 'object',
      categoryIds: ['technology', 'business', 'education', 'everyday_life'],
      domainIds: ['computers', 'programming', 'workplace'],
      tags: ['laptop', 'computer', 'screen', 'device'],
      aliases: ['notebook computer', 'macbook', 'pc laptop'],
      description: 'Clean modern laptop with glowing display screen.',
      generationPrompt: 'Sleek laptop computer open at 110 degrees, bright display showing code editor, Swallern blue accents.',
      targetComplexity: 'simple',
    },
    {
      id: 'server_rack_v1',
      name: 'server_rack',
      displayName: 'Datacenter Server Blade',
      family: 'object',
      categoryIds: ['technology'],
      domainIds: ['cloud_computing', 'networking'],
      tags: ['server', 'rack', 'datacenter', 'cloud'],
      aliases: ['server blade', 'datacenter rack'],
      description: 'Modular server rack unit with cyan activity lights.',
      generationPrompt: 'Datacenter blade server unit, high-contrast dark chassis, illuminated status indicators, clean vector.',
      targetComplexity: 'simple',
    },
    {
      id: 'router_v1',
      name: 'router',
      displayName: 'Wi-Fi Network Router',
      family: 'object',
      categoryIds: ['technology', 'communication_media'],
      domainIds: ['networking', 'internet'],
      tags: ['router', 'wifi', 'network', 'wireless'],
      aliases: ['wifi router', 'wireless router', 'network gateway'],
      description: 'Modern rounded wireless router with twin antennas.',
      generationPrompt: 'Modern Wi-Fi router, dual omnidirectional antennas, teal body, glowing signal lights, Swallern v1.',
      targetComplexity: 'simple',
    },
    {
      id: 'database_cylinder_v1',
      name: 'database_cylinder',
      displayName: 'Database Storage Stack',
      family: 'object',
      categoryIds: ['technology'],
      domainIds: ['software', 'datasets'],
      tags: ['database', 'sql', 'storage', 'data'],
      aliases: ['db cylinder', 'storage database'],
      description: 'Three stacked cylindrical database storage disks.',
      generationPrompt: 'Three stacked database storage cylinders, subtle glowing blue rings, clean perspective vector.',
      targetComplexity: 'simple',
    },
    {
      id: 'microchip_cpu_v1',
      name: 'microchip_cpu',
      displayName: 'Silicon Microprocessor CPU',
      family: 'object',
      categoryIds: ['technology', 'engineering'],
      domainIds: ['hardware', 'electronics'],
      tags: ['chip', 'cpu', 'processor', 'silicon'],
      aliases: ['cpu chip', 'microprocessor'],
      description: 'High-performance processor with golden pin grid and circuit traces.',
      generationPrompt: 'Square silicon CPU microchip, golden trace pathways, silver heat spreader, Swallern v1 vector.',
      targetComplexity: 'simple',
    },
  ],
};

export const FOUNDATION_PACK_3_SCIENCE: FoundationAssetPack = {
  packId: 'pack_3_science',
  title: 'Pack 3 — Physical & Life Science Essentials',
  description: 'Laboratory apparatus, atomic structures, optics, DNA molecules, and celestial bodies.',
  priority: 3,
  items: [
    {
      id: 'microscope_v1',
      name: 'microscope',
      displayName: 'Laboratory Microscope',
      family: 'object',
      categoryIds: ['science', 'health', 'medicine', 'education'],
      domainIds: ['laboratory', 'biology'],
      tags: ['microscope', 'lab', 'biology', 'optics'],
      aliases: ['optical microscope', 'lab scope'],
      description: 'Modern blue scientific microscope with stage and glass lens.',
      generationPrompt: 'Scientific optical microscope, Swallern blue and silver body, glass lens, clean vector silhouette.',
      targetComplexity: 'simple',
    },
    {
      id: 'dna_double_helix_v1',
      name: 'dna_double_helix',
      displayName: 'DNA Double Helix Strand',
      family: 'concept',
      categoryIds: ['science', 'health', 'medicine'],
      domainIds: ['biology', 'anatomy_pathology'],
      tags: ['dna', 'genetics', 'helix', 'nucleotides', 'genes'],
      aliases: ['dna strand', 'genetic code', 'double helix'],
      description: 'Colorful spiral double helix with paired nucleotide rungs.',
      generationPrompt: 'Stylized DNA double helix strand, spiral ladder with four colored base pairs, subtle depth gradients.',
      targetComplexity: 'moderate',
    },
    {
      id: 'atom_orbital_v1',
      name: 'atom_orbital',
      displayName: 'Atomic Nucleus & Electron Orbitals',
      family: 'object',
      categoryIds: ['science', 'energy'],
      domainIds: ['physics', 'chemistry'],
      tags: ['atom', 'electrons', 'nucleus', 'orbitals', 'protons'],
      aliases: ['atom model', 'bohr atom', 'atomic orbitals'],
      description: 'Stylized atomic nucleus encircled by three elliptical electron orbits.',
      generationPrompt: 'Atomic model with purple nucleus protons and orbiting teal electrons, clean symmetrical geometry.',
      targetComplexity: 'simple',
    },
    {
      id: 'flask_erlenmeyer_v1',
      name: 'flask_erlenmeyer',
      displayName: 'Erlenmeyer Reaction Flask',
      family: 'object',
      categoryIds: ['science', 'education'],
      domainIds: ['chemistry', 'laboratory'],
      tags: ['flask', 'chemistry', 'beaker', 'reaction'],
      aliases: ['conical flask', 'lab flask'],
      description: 'Conical glass flask containing bubbling teal chemical solution.',
      generationPrompt: 'Conical glass Erlenmeyer flask with bubbly teal liquid, volume measurement markings, soft glass shine.',
      targetComplexity: 'simple',
    },
  ],
};

export const FOUNDATION_PACK_4_AGRICULTURE: FoundationAssetPack = {
  packId: 'pack_4_agriculture',
  title: 'Pack 4 — Agriculture & Crop Cultivation Essentials',
  description: 'Seeds, soil cross-sections, crops, irrigation lines, tractors, and greenhouses.',
  priority: 4,
  items: [
    {
      id: 'seed_germinating_v1',
      name: 'seed_germinating',
      displayName: 'Germinating Seedling',
      family: 'object',
      categoryIds: ['agriculture', 'nature_environment', 'science'],
      domainIds: ['crops', 'botany'],
      tags: ['seed', 'sprout', 'germination', 'growth'],
      aliases: ['seedling', 'germinated seed'],
      description: 'Seed opening up with tender root and upward green shoot.',
      generationPrompt: 'Golden brown seed splitting with initial root tip downwards and tender green cotyledon upward.',
      targetComplexity: 'simple',
    },
    {
      id: 'tractor_green_v1',
      name: 'tractor_green',
      displayName: 'Farm Field Tractor',
      family: 'object',
      categoryIds: ['agriculture', 'transportation'],
      domainIds: ['machinery', 'road'],
      tags: ['tractor', 'farm', 'plow', 'machinery'],
      aliases: ['farm tractor', 'harvester tractor'],
      description: 'Green agricultural tractor with oversized treaded rear tires.',
      generationPrompt: 'Vibrant green farm tractor, oversized ribbed tires, glass cab, Swallern v1 soft vector geometry.',
      targetComplexity: 'moderate',
    },
    {
      id: 'irrigation_sprinkler_v1',
      name: 'irrigation_sprinkler',
      displayName: 'Precision Field Sprinkler',
      family: 'object',
      categoryIds: ['agriculture', 'engineering'],
      domainIds: ['irrigation', 'civil'],
      tags: ['irrigation', 'sprinkler', 'water', 'conservation'],
      aliases: ['crop sprinkler', 'water emitter'],
      description: 'Pivot irrigation sprinkler emitting a gentle arc of blue water droplets.',
      generationPrompt: 'Agricultural irrigation sprinkler head spraying fine water arc, crisp blue droplets, clean vector.',
      targetComplexity: 'simple',
    },
  ],
};

export const FOUNDATION_PACK_5_BUSINESS: FoundationAssetPack = {
  packId: 'pack_5_business',
  title: 'Pack 5 — Business, Commerce & Finance Essentials',
  description: 'Financial institutions, banknotes, payment cards, market charts, and office artifacts.',
  priority: 5,
  items: [
    {
      id: 'bank_branch_v1',
      name: 'bank_branch',
      displayName: 'Bank Financial Institution',
      family: 'object',
      categoryIds: ['finance_economics', 'business', 'architecture_construction'],
      domainIds: ['banking', 'building_design'],
      tags: ['bank', 'financial', 'vault', 'institution'],
      aliases: ['bank building', 'commercial bank'],
      description: 'Bank building with classical columns and solid security vault doors.',
      generationPrompt: 'Neoclassical bank building, rounded columns, navy pediment, secure vault detail, clean vector.',
      targetComplexity: 'moderate',
    },
    {
      id: 'credit_card_digital_v1',
      name: 'credit_card_digital',
      displayName: 'Smart Payment Card',
      family: 'object',
      categoryIds: ['finance_economics', 'business', 'technology'],
      domainIds: ['banking', 'sales_commerce', 'cybersecurity'],
      tags: ['card', 'payment', 'credit', 'chip'],
      aliases: ['debit card', 'smart card'],
      description: 'Modern gradient payment card with EMV gold chip.',
      generationPrompt: 'Floating modern payment card, purple-to-blue gradient, gold EMV contact chip, contactless icon.',
      targetComplexity: 'simple',
    },
    {
      id: 'analytics_chart_v1',
      name: 'analytics_chart',
      displayName: 'Ascending Growth Bar Chart',
      family: 'object',
      categoryIds: ['business', 'finance_economics', 'mathematics'],
      domainIds: ['operations', 'markets', 'probability_stats'],
      tags: ['chart', 'analytics', 'growth', 'metrics', 'bars'],
      aliases: ['bar graph', 'growth chart', 'metrics display'],
      description: 'Ascending three-dimensional rounded bar graph with upward trend arrow.',
      generationPrompt: 'Ascending bar graph with four pillars, teal and green bars, golden upward trajectory arrow.',
      targetComplexity: 'simple',
    },
  ],
};

export const FOUNDATION_PACK_6_NATURE: FoundationAssetPack = {
  packId: 'pack_6_nature',
  title: 'Pack 6 — Nature, Habitats & Wildlife Essentials',
  description: 'Forests, mountain ranges, river basins, ocean depths, and ecological elements.',
  priority: 6,
  items: [
    {
      id: 'mountain_snowcap_v1',
      name: 'mountain_snowcap',
      displayName: 'Snowcapped Alpine Mountain',
      family: 'object',
      categoryIds: ['nature_environment', 'geography'],
      domainIds: ['physical_geography', 'ecosystems'],
      tags: ['mountain', 'peak', 'snow', 'alps', 'range'],
      aliases: ['snowy mountain', 'alpine peak'],
      description: 'Soft triangular mountain with clean white snowcap under blue sky.',
      generationPrompt: 'Majestic rounded alpine mountain peak, pristine snowcap, navy rock base, soft sky backdrop.',
      targetComplexity: 'simple',
    },
    {
      id: 'river_stream_v1',
      name: 'river_stream',
      displayName: 'Flowing Mountain River',
      family: 'object',
      categoryIds: ['nature_environment', 'geography'],
      domainIds: ['physical_geography', 'ecosystems'],
      tags: ['river', 'stream', 'water', 'flow', 'meadow'],
      aliases: ['freshwater stream', 'winding river'],
      description: 'Winding crystal-clear blue river meandering through green riverbanks.',
      generationPrompt: 'Winding blue river stream flowing between smooth green banks with rounded river stones.',
      targetComplexity: 'moderate',
    },
    {
      id: 'ocean_wave_v1',
      name: 'ocean_wave',
      displayName: 'Rolling Ocean Wave',
      family: 'object',
      categoryIds: ['nature_environment', 'science', 'geography'],
      domainIds: ['ecosystems', 'physical_geography'],
      tags: ['ocean', 'wave', 'sea', 'water', 'marine'],
      aliases: ['sea wave', 'surf wave'],
      description: 'Smooth curled ocean wave crest with white seafoam.',
      generationPrompt: 'Curling ocean wave crest, deep blue to cyan gradient, rounded white foam bubbles, clean vector.',
      targetComplexity: 'simple',
    },
  ],
};

export const ALL_FOUNDATION_PACKS: FoundationAssetPack[] = [
  FOUNDATION_PACK_1_UNIVERSAL,
  FOUNDATION_PACK_2_TECHNOLOGY,
  FOUNDATION_PACK_3_SCIENCE,
  FOUNDATION_PACK_4_AGRICULTURE,
  FOUNDATION_PACK_5_BUSINESS,
  FOUNDATION_PACK_6_NATURE,
];
