/**
 * Swallern Visual System v1 — Master Objects Library
 * Section 6 & 31: Reusable physical objects with multi-category semantic domain memberships.
 * A single canonical asset (e.g. 'laptop_v1') serves technology, business, education, etc.
 */

import { VisualAsset } from './assets';
import { SWALLERN_VISUAL_STYLE_V1 } from './tokens';

export type ObjectCategory = 'learning' | 'science' | 'exploration' | 'nature' | 'history' | 'technology' | 'agriculture' | 'business' | 'everyday';

export interface EducationalObjectSpec {
  assetId: string;
  name: string;
  category: ObjectCategory;
  description: string;
  renderingStyle: string;
  defaultColor: string;
}

/**
 * Legacy Object Library (preserved for backward compatibility)
 */
export const SWALLERN_OBJECT_LIBRARY: Record<string, EducationalObjectSpec> = {
  // Learning & Everyday
  swallern_book_v1: {
    assetId: 'swallern_book_v1',
    name: 'Educational Book',
    category: 'learning',
    description: 'Open hardcover book with clean thick pages and rounded spine',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#3B82F6',
  },
  swallern_notebook_v1: {
    assetId: 'swallern_notebook_v1',
    name: 'Study Notebook',
    category: 'learning',
    description: 'Spiral notebook with bookmark tab and clean lines',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#0D9488',
  },
  swallern_pencil_v1: {
    assetId: 'swallern_pencil_v1',
    name: 'Yellow Pencil',
    category: 'learning',
    description: 'Classic yellow graphite pencil with pink eraser tip',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#F59E0B',
  },
  swallern_blackboard_v1: {
    assetId: 'swallern_blackboard_v1',
    name: 'Classroom Slate',
    category: 'learning',
    description: 'Dark green wooden frame blackboard with clean chalk drawings',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#064E3B',
  },
  swallern_flashcard_v1: {
    assetId: 'swallern_flashcard_v1',
    name: 'Knowledge Flashcard',
    category: 'learning',
    description: 'Rounded white card with vivid colored header line',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#8B5CF6',
  },
  swallern_lightbulb_v1: {
    assetId: 'swallern_lightbulb_v1',
    name: 'Idea Lightbulb',
    category: 'learning',
    description: 'Glowing yellow lightbulb with soft spark dots',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#F59E0B',
  },

  // Science
  swallern_microscope_v1: {
    assetId: 'swallern_microscope_v1',
    name: 'Laboratory Microscope',
    category: 'science',
    description: 'Modern blue scientific microscope with stage and glass lens',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#3B82F6',
  },
  swallern_flask_v1: {
    assetId: 'swallern_flask_v1',
    name: 'Erlenmeyer Flask',
    category: 'science',
    description: 'Conical glass flask containing bubbly teal liquid',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#0D9488',
  },
  swallern_testtube_v1: {
    assetId: 'swallern_testtube_v1',
    name: 'Test Tubes Rack',
    category: 'science',
    description: 'Wooden rack holding 3 test tubes with colorful liquids',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#10B981',
  },
  swallern_atom_v1: {
    assetId: 'swallern_atom_v1',
    name: 'Atomic Structure',
    category: 'science',
    description: 'Stylized atomic nucleus with orbital electron rings',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#8B5CF6',
  },
  swallern_telescope_v1: {
    assetId: 'swallern_telescope_v1',
    name: 'Astronomical Telescope',
    category: 'science',
    description: 'Brass and navy telescope mounted on tripod pointed at stars',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#0F172A',
  },
  swallern_magnet_v1: {
    assetId: 'swallern_magnet_v1',
    name: 'Horseshoe Magnet',
    category: 'science',
    description: 'Red and blue horseshoe magnet with magnetic field lines',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#EF4444',
  },

  // Exploration
  swallern_globe_v1: {
    assetId: 'swallern_globe_v1',
    name: 'World Globe',
    category: 'exploration',
    description: 'Desktop globe with blue oceans and green landmasses',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#3B82F6',
  },
  swallern_compass_v1: {
    assetId: 'swallern_compass_v1',
    name: 'Explorer Compass',
    category: 'exploration',
    description: 'Brass magnetic compass with N/S/E/W markings and red needle',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#F59E0B',
  },
  swallern_magnifying_glass_v1: {
    assetId: 'swallern_magnifying_glass_v1',
    name: 'Magnifying Lens',
    category: 'exploration',
    description: 'Round glass magnifying lens with wooden handle',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#3B82F6',
  },

  // Nature
  swallern_plant_v1: {
    assetId: 'swallern_plant_v1',
    name: 'Potted Plant',
    category: 'nature',
    description: 'Vibrant green leafy sprout in terracotta pot',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#10B981',
  },
  swallern_mountain_v1: {
    assetId: 'swallern_mountain_v1',
    name: 'Snowcapped Peak',
    category: 'nature',
    description: 'Soft rounded mountain range with white snow peaks',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#0F172A',
  },
  swallern_sun_v1: {
    assetId: 'swallern_sun_v1',
    name: 'Bright Sun',
    category: 'nature',
    description: 'Warm yellow sun with soft rounded rays',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#F59E0B',
  },

  // History
  swallern_scroll_v1: {
    assetId: 'swallern_scroll_v1',
    name: 'Ancient Parchment Scroll',
    category: 'history',
    description: 'Unrolled beige parchment scroll with red ribbon seal',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#D2B48C',
  },
  swallern_pyramid_v1: {
    assetId: 'swallern_pyramid_v1',
    name: 'Sandstone Pyramid',
    category: 'history',
    description: 'Geometric sandstone pyramid against clear sky',
    renderingStyle: 'Swallern v1 soft geometry vector',
    defaultColor: '#F59E0B',
  },
};

export function getObjectSpec(assetId: string): EducationalObjectSpec | null {
  return SWALLERN_OBJECT_LIBRARY[assetId] || null;
}

/**
 * Master Canonical Object Visual Assets (Typed as VisualAsset with Multi-Category Tags)
 */
export const CANONICAL_OBJECT_ASSETS: VisualAsset[] = [
  // Technology Objects
  {
    id: 'laptop_v1',
    version: '1.0',
    name: 'laptop',
    displayName: 'Modern Laptop',
    family: 'object',
    categoryIds: ['technology', 'business', 'education', 'everyday_life'],
    domainIds: ['computers', 'programming', 'workplace', 'classroom_learning'],
    tags: ['laptop', 'computer', 'notebook', 'screen', 'device', 'programming'],
    aliases: ['notebook computer', 'portable computer', 'macbook', 'pc laptop'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'router_v1', 'smartphone_v1', 'server_v1', 'desk_v1'],
    description: 'Clean modern laptop with bright screen, rounded aluminum body, and soft keyboard details.',
    defaultColor: '#3B82F6',
  },
  {
    id: 'desktop_v1',
    version: '1.0',
    name: 'desktop_computer',
    displayName: 'Desktop Computer & Monitor',
    family: 'object',
    categoryIds: ['technology', 'business', 'education'],
    domainIds: ['computers', 'workplace'],
    tags: ['desktop', 'monitor', 'pc', 'workstation', 'screen'],
    aliases: ['desktop pc', 'workstation', 'computer monitor'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['keyboard_v1', 'mouse_v1', 'desk_v1'],
    description: 'Sleek desktop workstation with high-resolution wide screen on minimalist stand.',
    defaultColor: '#0F172A',
  },
  {
    id: 'smartphone_v1',
    version: '1.0',
    name: 'smartphone',
    displayName: 'Smartphone',
    family: 'object',
    categoryIds: ['technology', 'communication_media', 'everyday_life'],
    domainIds: ['computers', 'telecommunications', 'home_daily'],
    tags: ['smartphone', 'mobile', 'phone', 'touchscreen', 'device'],
    aliases: ['mobile phone', 'cell phone', 'handset'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'router_v1', 'laptop_v1', 'signal_waves_v1'],
    description: 'Rounded glass touchscreen phone with friendly app icon layout.',
    defaultColor: '#3B82F6',
  },
  {
    id: 'tablet_v1',
    version: '1.0',
    name: 'tablet',
    displayName: 'Touchscreen Tablet',
    family: 'object',
    categoryIds: ['technology', 'education', 'arts_design'],
    domainIds: ['computers', 'classroom_learning', 'graphic_design'],
    tags: ['tablet', 'ipad', 'touchscreen', 'drawing_pad'],
    aliases: ['digital tablet', 'drawing tablet', 'pad'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'stylus_v1'],
    description: 'Slim digital tablet device with colorful interface display.',
    defaultColor: '#8B5CF6',
  },
  {
    id: 'router_v1',
    version: '1.0',
    name: 'router',
    displayName: 'Wi-Fi Network Router',
    family: 'object',
    categoryIds: ['technology', 'communication_media'],
    domainIds: ['networking', 'internet'],
    tags: ['router', 'wifi', 'network', 'wireless', 'internet', 'broadband'],
    aliases: ['wifi router', 'wireless router', 'network gateway'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['laptop_v1', 'smartphone_v1', 'server_v1', 'network_signal_v1', 'network_nodes_v1'],
    description: 'Modern rounded wireless router with twin antennas and blinking status LED dots.',
    defaultColor: '#0D9488',
  },
  {
    id: 'server_v1',
    version: '1.0',
    name: 'server',
    displayName: 'Rack Server Blade',
    family: 'object',
    categoryIds: ['technology'],
    domainIds: ['cloud_computing', 'networking'],
    tags: ['server', 'rack', 'datacenter', 'backend', 'cloud', 'storage'],
    aliases: ['server rack', 'blade server', 'datacenter server'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['router_v1', 'cloud_network_v1', 'database_v1'],
    description: 'High-density server rack unit with cool cyan activity indicator lights.',
    defaultColor: '#0F172A',
  },
  {
    id: 'chip_v1',
    version: '1.0',
    name: 'microchip',
    displayName: 'Microprocessor Chip',
    family: 'object',
    categoryIds: ['technology', 'engineering'],
    domainIds: ['hardware', 'electronics'],
    tags: ['chip', 'processor', 'cpu', 'semiconductor', 'silicon'],
    aliases: ['cpu', 'processor', 'microcontroller', 'silicon chip'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['circuit_board_v1'],
    description: 'Gold-pinned semiconductor processor chip with geometric circuit etchings.',
    defaultColor: '#F59E0B',
  },
  {
    id: 'circuit_board_v1',
    version: '1.0',
    name: 'circuit_board',
    displayName: 'Electronic Circuit Board',
    family: 'object',
    categoryIds: ['technology', 'engineering'],
    domainIds: ['electronics', 'hardware'],
    tags: ['circuit', 'pcb', 'electronics', 'motherboard', 'traces'],
    aliases: ['pcb', 'printed circuit board', 'motherboard'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['chip_v1'],
    description: 'Teal circuit board with golden soldered pathways and capacitor components.',
    defaultColor: '#0D9488',
  },
  {
    id: 'robot_v1',
    version: '1.0',
    name: 'robot',
    displayName: 'Educational Assistant Robot',
    family: 'object',
    categoryIds: ['technology', 'artificial_intelligence', 'engineering'],
    domainIds: ['robotics', 'ai_agents'],
    tags: ['robot', 'bot', 'android', 'automation', 'mechanic'],
    aliases: ['robot assistant', 'ai bot', 'android'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['swallern_bear_v1', 'laptop_v1'],
    description: 'Friendly rounded humanoid robot with glowing cyan screen visor and jointed arms.',
    defaultColor: '#3B82F6',
  },
  {
    id: 'drone_v1',
    version: '1.0',
    name: 'drone',
    displayName: 'Autonomous Quadcopter Drone',
    family: 'object',
    categoryIds: ['technology', 'agriculture', 'transportation'],
    domainIds: ['robotics', 'agtech', 'road'],
    tags: ['drone', 'quadcopter', 'aerial', 'surveillance', 'sensors'],
    aliases: ['uav', 'quadcopter', 'aerial drone'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['camera_v1', 'tractor_v1'],
    description: 'Aerodynamic four-rotor drone equipped with sensor gimbal camera.',
    defaultColor: '#0F172A',
  },

  // Science Objects
  {
    id: 'microscope_v1',
    version: '1.0',
    name: 'microscope',
    displayName: 'Laboratory Microscope',
    family: 'object',
    categoryIds: ['science', 'health', 'medicine', 'education'],
    domainIds: ['laboratory', 'biology', 'clinical_care'],
    tags: ['microscope', 'lab', 'biology', 'optics', 'magnify', 'cells'],
    aliases: ['lab microscope', 'optical microscope'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'test_tube_v1', 'flask_v1'],
    description: 'Modern blue optical microscope with stage clips and dual focus dials.',
    defaultColor: '#3B82F6',
  },
  {
    id: 'telescope_v1',
    version: '1.0',
    name: 'telescope',
    displayName: 'Astronomical Telescope',
    family: 'object',
    categoryIds: ['space', 'science', 'education'],
    domainIds: ['astronomy', 'physics'],
    tags: ['telescope', 'stars', 'space', 'astronomy', 'optics', 'planets'],
    aliases: ['refractor telescope', 'astronomy scope'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'stars_ambient_v1'],
    description: 'Navy and brass telescope positioned on a sturdy wooden tripod.',
    defaultColor: '#0F172A',
  },
  {
    id: 'flask_v1',
    version: '1.0',
    name: 'flask',
    displayName: 'Erlenmeyer Flask',
    family: 'object',
    categoryIds: ['science', 'education'],
    domainIds: ['chemistry', 'laboratory'],
    tags: ['flask', 'chemistry', 'beaker', 'liquid', 'experiment'],
    aliases: ['erlenmeyer flask', 'conical flask', 'lab beaker'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['test_tube_v1', 'microscope_v1'],
    description: 'Conical glass laboratory flask with calibrated tick marks and bubbly teal liquid.',
    defaultColor: '#0D9488',
  },
  {
    id: 'test_tube_v1',
    version: '1.0',
    name: 'test_tube',
    displayName: 'Test Tubes Rack',
    family: 'object',
    categoryIds: ['science', 'medicine'],
    domainIds: ['chemistry', 'laboratory', 'pharmacy'],
    tags: ['test_tube', 'chemistry', 'lab', 'reagents', 'solutions'],
    aliases: ['test tubes', 'vials', 'lab tubes'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['flask_v1', 'microscope_v1'],
    description: 'Wooden test tube rack with glass cylinders containing vibrant solutions.',
    defaultColor: '#10B981',
  },
  {
    id: 'magnet_v1',
    version: '1.0',
    name: 'magnet',
    displayName: 'Horseshoe Magnet',
    family: 'object',
    categoryIds: ['science', 'education', 'engineering'],
    domainIds: ['physics', 'electrical'],
    tags: ['magnet', 'magnetic', 'poles', 'physics', 'attraction'],
    aliases: ['horseshoe magnet', 'permanent magnet'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['iron_filings_v1'],
    description: 'Classic red and blue horseshoe magnet with silver contact tips.',
    defaultColor: '#EF4444',
  },

  // Agriculture Objects
  {
    id: 'seed_v1',
    version: '1.0',
    name: 'seed',
    displayName: 'Germinating Plant Seed',
    family: 'object',
    categoryIds: ['agriculture', 'nature_environment', 'science'],
    domainIds: ['crops', 'botany', 'biology'],
    tags: ['seed', 'plant', 'germination', 'sprout', 'growth'],
    aliases: ['seedling', 'plant seed', 'grain seed'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['soil_v1', 'watering_can_v1', 'crop_plant_v1'],
    description: 'Golden-brown organic seed with tiny green initial root sprout.',
    defaultColor: '#F59E0B',
  },
  {
    id: 'soil_v1',
    version: '1.0',
    name: 'soil',
    displayName: 'Fertile Soil Layer',
    family: 'object',
    categoryIds: ['agriculture', 'nature_environment'],
    domainIds: ['soil', 'botany'],
    tags: ['soil', 'earth', 'ground', 'dirt', 'compost', 'nutrients'],
    aliases: ['topsoil', 'fertile earth', 'compost layer'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['seed_v1', 'crop_plant_v1', 'watering_can_v1', 'irrigation_pipe_v1'],
    description: 'Rich dark-brown layered soil cross-section with mineral textures.',
    defaultColor: '#78350F',
  },
  {
    id: 'watering_can_v1',
    version: '1.0',
    name: 'watering_can',
    displayName: 'Garden Watering Can',
    family: 'object',
    categoryIds: ['agriculture', 'nature_environment', 'everyday_life'],
    domainIds: ['crops', 'botany', 'home_daily'],
    tags: ['water', 'watering_can', 'gardening', 'irrigation', 'plants'],
    aliases: ['gardening can', 'sprinkler can'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['seed_v1', 'soil_v1', 'crop_plant_v1'],
    description: 'Teal galvanized watering can dispensing clear droplets of water.',
    defaultColor: '#0D9488',
  },
  {
    id: 'tractor_v1',
    version: '1.0',
    name: 'tractor',
    displayName: 'Agricultural Tractor',
    family: 'object',
    categoryIds: ['agriculture', 'transportation'],
    domainIds: ['machinery', 'road'],
    tags: ['tractor', 'farm', 'machinery', 'harvest', 'plow'],
    aliases: ['farm tractor', 'plowing tractor'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['farm_field_v1', 'plow_v1'],
    description: 'Vibrant green tractor with oversized treaded wheels and driver cabin.',
    defaultColor: '#10B981',
  },
  {
    id: 'irrigation_pipe_v1',
    version: '1.0',
    name: 'irrigation_pipe',
    displayName: 'Drip Irrigation Tube',
    family: 'object',
    categoryIds: ['agriculture', 'engineering'],
    domainIds: ['irrigation', 'civil'],
    tags: ['irrigation', 'pipe', 'drip', 'water', 'conservation'],
    aliases: ['drip tube', 'irrigation canal', 'water pipe'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['soil_v1', 'crop_plant_v1'],
    description: 'Modular irrigation pipe with precision micro-emitters spraying water mist.',
    defaultColor: '#3B82F6',
  },

  // Business & Finance Objects
  {
    id: 'bank_building_v1',
    version: '1.0',
    name: 'bank_building',
    displayName: 'Financial Bank Branch',
    family: 'object',
    categoryIds: ['finance_economics', 'business', 'architecture_construction'],
    domainIds: ['banking', 'sales_commerce', 'building_design'],
    tags: ['bank', 'financial', 'institution', 'money', 'vault'],
    aliases: ['bank', 'credit union', 'financial institution'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'moderate',
    compatibleWith: ['money_coins_v1', 'credit_card_v1', 'person_v1'],
    description: 'Classic neoclassical bank building with rounded pillars and vault motif.',
    defaultColor: '#0F172A',
  },
  {
    id: 'money_coins_v1',
    version: '1.0',
    name: 'money_coins',
    displayName: 'Currency Coins & Notes',
    family: 'object',
    categoryIds: ['finance_economics', 'business', 'everyday_life'],
    domainIds: ['banking', 'personal_finance', 'sales_commerce'],
    tags: ['money', 'coins', 'cash', 'currency', 'wealth', 'payment'],
    aliases: ['cash', 'currency', 'dollar coins', 'banknotes'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['bank_building_v1', 'credit_card_v1', 'piggy_bank_v1'],
    description: 'Stack of gleaming golden coins beside crisp folded currency banknotes.',
    defaultColor: '#F59E0B',
  },
  {
    id: 'credit_card_v1',
    version: '1.0',
    name: 'credit_card',
    displayName: 'Digital Payment Card',
    family: 'object',
    categoryIds: ['finance_economics', 'business', 'technology'],
    domainIds: ['banking', 'sales_commerce', 'cybersecurity'],
    tags: ['card', 'payment', 'credit', 'debit', 'contactless', 'chip'],
    aliases: ['debit card', 'smart card', 'visa card'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['bank_building_v1', 'smartphone_v1', 'laptop_v1'],
    description: 'Vivid gradient credit card with EMV chip and contactless waves.',
    defaultColor: '#8B5CF6',
  },
  {
    id: 'briefcase_v1',
    version: '1.0',
    name: 'briefcase',
    displayName: 'Executive Briefcase',
    family: 'object',
    categoryIds: ['business', 'everyday_life'],
    domainIds: ['workplace', 'management'],
    tags: ['briefcase', 'work', 'office', 'executive', 'documents'],
    aliases: ['work bag', 'attache case'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['business_person_v1', 'laptop_v1', 'desk_v1'],
    description: 'Clean leather executive briefcase with brass latch locks.',
    defaultColor: '#78350F',
  },

  // Everyday & Classroom Objects
  {
    id: 'book_v1',
    version: '1.0',
    name: 'book',
    displayName: 'Educational Book',
    family: 'object',
    categoryIds: ['education', 'literature_language', 'everyday_life'],
    domainIds: ['classroom_learning', 'storytelling', 'home_daily'],
    tags: ['book', 'reading', 'textbook', 'pages', 'study', 'knowledge'],
    aliases: ['textbook', 'handbook', 'reading book'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'desk_v1', 'backpack_v1', 'pencil_v1'],
    description: 'Open hardcover book with clean thick pages and rounded spine.',
    defaultColor: '#3B82F6',
  },
  {
    id: 'pencil_v1',
    version: '1.0',
    name: 'pencil',
    displayName: 'Graphite Pencil',
    family: 'object',
    categoryIds: ['education', 'arts_design', 'everyday_life'],
    domainIds: ['classroom_learning', 'visual_art', 'home_daily'],
    tags: ['pencil', 'writing', 'sketching', 'stationery', 'drawing'],
    aliases: ['yellow pencil', 'graphite pencil', 'pen'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['book_v1', 'notebook_v1', 'swallern_bear_v1'],
    description: 'Classic yellow graphite pencil with pink eraser tip.',
    defaultColor: '#F59E0B',
  },
  {
    id: 'backpack_v1',
    version: '1.0',
    name: 'backpack',
    displayName: 'Student Backpack',
    family: 'object',
    categoryIds: ['education', 'everyday_life', 'travel_exploration'],
    domainIds: ['classroom_learning', 'home_daily', 'expedition_travel'],
    tags: ['backpack', 'bag', 'school', 'supplies', 'rucksack'],
    aliases: ['school bag', 'rucksack', 'knapsack'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['swallern_bear_v1', 'book_v1', 'pencil_v1'],
    description: 'Iconic bright Swallern Blue backpack with yellow zipper pulls and dual straps.',
    defaultColor: '#3B82F6',
  },
  {
    id: 'desk_v1',
    version: '1.0',
    name: 'desk',
    displayName: 'Wooden Study & Office Desk',
    family: 'object',
    categoryIds: ['education', 'business', 'everyday_life'],
    domainIds: ['classroom_learning', 'workplace', 'home_daily'],
    tags: ['desk', 'table', 'workspace', 'furniture', 'study'],
    aliases: ['study desk', 'office table', 'workstation'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['laptop_v1', 'book_v1', 'lamp_v1', 'chair_v1'],
    description: 'Smooth wooden desk with clean legs and ample workspace area.',
    defaultColor: '#D2B48C',
  },
  {
    id: 'chair_v1',
    version: '1.0',
    name: 'chair',
    displayName: 'Ergonomic Desk Chair',
    family: 'object',
    categoryIds: ['education', 'business', 'everyday_life'],
    domainIds: ['classroom_learning', 'workplace', 'home_daily'],
    tags: ['chair', 'seat', 'furniture', 'office', 'study'],
    aliases: ['desk chair', 'office chair', 'study chair'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['desk_v1', 'swallern_bear_v1'],
    description: 'Modern rounded ergonomic desk chair with supportive backrest.',
    defaultColor: '#0F172A',
  },
  {
    id: 'clock_v1',
    version: '1.0',
    name: 'clock',
    displayName: 'Analog Wall Clock',
    family: 'object',
    categoryIds: ['education', 'everyday_life'],
    domainIds: ['classroom_learning', 'home_daily'],
    tags: ['clock', 'time', 'hours', 'minutes', 'seconds', 'schedule'],
    aliases: ['wall clock', 'analog clock', 'timer'],
    visualStyle: SWALLERN_VISUAL_STYLE_V1,
    assetType: 'illustration',
    source: 'curated_builtin',
    status: 'active',
    reusable: true,
    complexity: 'simple',
    compatibleWith: ['desk_v1', 'classroom_bg_v1'],
    description: 'Clean circular clock with readable hour numbers and ticking hands.',
    defaultColor: '#0F172A',
  },
];
